const countries = [
    { "name": "Argentina", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/argentina-circular.png\" alt=\"argentina-circular\"/>" },
    { "name": "Australia", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/australia-circular.png\" alt=\"australia-circular\"/>" },
    { "name": "Austria", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/austria-circular.png\" alt=\"austria-circular\"/>" },
    { "name": "Belgium", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/belgium-circular.png\" alt=\"belgium-circular\"/>" },
    { "name": "Brazil", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/brazil-circular.png\" alt=\"brazil-circular\"/>" },
    { "name": "Cameroon", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/cameroon-circular.png\" alt=\"cameroon-circular\"/>" },
    { "name": "Canada", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/canada-circular.png\" alt=\"canada-circular\"/>" },
    { "name": "Chile", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/chile-circular.png\" alt=\"chile-circular\"/>" },
    { "name": "China", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/china-circular.png\" alt=\"china-circular\"/>" },
    { "name": "Colombia", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/colombia-circular.png\" alt=\"colombia-circular\"/>" },
    { "name": "Croatia", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/croatia-circular.png\" alt=\"croatia-circular\"/>" },
    { "name": "Czech Republic", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/czech-republic-circular.png\" alt=\"czech-republic-circular\"/>" },
    { "name": "Denmark", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/denmark-circular.png\" alt=\"denmark-circular\"/>" },
    { "name": "Ecuador", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/ecuador-circular.png\" alt=\"ecuador-circular\"/>" },
    { "name": "Egypt", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/egypt-circular.png\" alt=\"egypt-circular\"/>" },
    { "name": "England", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/england-circular.png\" alt=\"england-circular\"/>" },
    { "name": "France", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/france-circular.png\" alt=\"france-circular\"/>" },
    { "name": "Germany", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/germany-circular.png\" alt=\"germany-circular\"/>" },
    { "name": "Greece", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/greece-circular.png\" alt=\"greece-circular\"/>" },
    { "name": "Iceland", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/iceland-circular.png\" alt=\"iceland-circular\"/>" },
    { "name": "India", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/india-circular.png\" alt=\"india-circular\"/>" },
    { "name": "Iran", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/iran-circular.png\" alt=\"iran-circular\"/>" },
    { "name": "Iraq", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/iraq-circular.png\" alt=\"iraq-circular\"/>" },
    { "name": "Ireland", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/ireland-circular.png\" alt=\"ireland-circular\"/>" },
    { "name": "Israel", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/israel-circular.png\" alt=\"israel-circular\"/>" },
    { "name": "Italy", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/italy-circular.png\" alt=\"italy-circular\"/>" },
    { "name": "Jamaica", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/jamaica-circular.png\" alt=\"jamaica-circular\"/>" },
    { "name": "Japan", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/japan-circular.png\" alt=\"japan-circular\"/>" },
    { "name": "Kuwait", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/kuwait-circular.png\" alt=\"kuwait-circular\"/>" },
    { "name": "Mexico", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/mexico-circular.png\" alt=\"mexico-circular\"/>" },
    { "name": "Netherlands", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/netherlands-circular.png\" alt=\"netherlands-circular\"/>" },
    { "name": "New Zealand", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/new-zealand-circular.png\" alt=\"new-zealand-circular\"/>" },
    { "name": "Norway", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/norway-circular.png\" alt=\"norway-circular\"/>" },
    { "name": "Paraguay", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/paraguay-circular.png\" alt=\"paraguay-circular\"/>" },
    { "name": "Peru", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/peru-circular.png\" alt=\"peru-circular\"/>" },
    { "name": "Poland", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/poland-circular.png\" alt=\"poland-circular\"/>" },
    { "name": "Portugal", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/portugal-circular.png\" alt=\"portugal-circular\"/>" },
    { "name": "Qatar", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/qatar-circular.png\" alt=\"qatar-circular\"/>" },
    { "name": "Romania", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/romania-circular.png\" alt=\"romania-circular\"/>" },
    { "name": "Saudi Arabia", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/saudi-arabia-circular.png\" alt=\"saudi-arabia-circular\"/>" },
    { "name": "Scotland", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/scotland-circular.png\" alt=\"scotland-circular\"/>" },
    { "name": "South Africa", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/south-africa-circular.png\" alt=\"south-africa-circular\"/>" },
    { "name": "South Korea", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/south-korea-circular.png\" alt=\"south-korea-circular\"/>" },
    { "name": "Spain", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/spain-circular.png\" alt=\"spain-circular\"/>" },
    { "name": "Sweden", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/sweden-circular.png\" alt=\"sweden-circular\"/>" },
    { "name": "Switzerland", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/switzerland-circular.png\" alt=\"switzerland-circular\"/>" },
    { "name": "Turkey", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/turkey-circular.png\" alt=\"turkey-circular\"/>" },
    { "name": "Ukraine", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/ukraine-circular.png\" alt=\"ukraine-circular\"/>" },
    { "name": "United Arab Emirates", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/united-arab-emirates-circular.png\" alt=\"united-arab-emirates-circular\"/>" },
    { "name": "United States", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/usa-circular.png\" alt=\"usa-circular\"/>" },
    { "name": "Uruguay", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/uruguay-circular.png\" alt=\"uruguay-circular\"/>" },
    { "name": "Wales", "flag": "<img width=\"96\" height=\"96\" src=\"https://img.icons8.com/fluency/96/wales-circular.png\" alt=\"wales-circular\"/>" }
]